const quizQuestions = [
    {
        id: 1,
        textStructure: [{w: "文中", p: "wén zhōng"}, "“", {w: "妻乃引刀趋机", p: "qī nǎi yǐn dāo qū jī"}, "”", {w: "中的", p: "zhōng de"}, "“", {w: "趋", p: "qū"}, "”", {w: "字正确的", p: "zì zhèng què de"}, {w: "词义是", p: "cí yì shì"}, "？"],
        en: "What is the correct meaning of the character 'qū' in this context?",
        options: [
            { textStructure: [{w: "动词", p: "dòng cí"}, "，", {w: "意为", p: "yì wéi"}, "“", {w: "快步走向", p: "kuài bù zǒu xiàng"}, "”", {w: "织布机处", p: "zhī bù jī chù"}], en: "A verb, meaning 'to step forward quickly' towards the loom.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "古汉语中", p: "gǔ hàn yǔ zhōng"}, "“", {w: "趋", p: "qū"}, "”", {w: "指小步快走", p: "zhǐ xiǎo bù kuài zǒu"}, "，", {w: "表动作紧急", p: "biǎo dòng zuò jǐn jí"}, "。"], explanationEn: "Correct. In classical Chinese, 'qū' means to walk quickly or rush forward, reflecting her urgent mental state." },
            { textStructure: [{w: "动词", p: "dòng cí"}, "，", {w: "意为", p: "yì wéi"}, "“", {w: "用力推开", p: "yòng lì tuī kāi"}, "”", {w: "织布机架", p: "zhī bù jī jià"}], en: "A verb, meaning 'to push away forcefully' the wooden frame.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "字义不符", p: "zì yì bù fú"}, "，", {w: "这误解了字形", p: "zhè wù jiě le zì xíng"}, {w: "造成的单纯瞎猜", p: "zào chéng de dān chún xiā cāi"}, "。"], explanationEn: "Incorrect. This entirely misrepresents the character's physical definition based on pure visual guessing." },
            { textStructure: [{w: "动词", p: "dòng cí"}, "，", {w: "意为", p: "yì wéi"}, "“", {w: "低头查看", p: "dī tóu chá kàn"}, "”", {w: "织布成品", p: "zhī bù chéng pǐn"}], en: "A verb, meaning 'to bend down and examine' the fabric details.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "语境不符", p: "yǔ jìng bù fú"}, "，", {w: "她当时怒其不争", p: "tā dāng shí nù qí bù zhēng"}, {w: "正准备断织", p: "zhèng zhǔn bèi duàn zhī"}, "。"], explanationEn: "Incorrect. She was preparing to cut the cloth in anger, not casually checking production flaws." },
            { textStructure: [{w: "动词", p: "dòng cí"}, "，", {w: "意为", p: "yì wéi"}, "“", {w: "大刀阔步", p: "dà dāo kuò bù"}, "”", {w: "走向远方", p: "zǒu xiàng yuǎn fāng"}], en: "A verb, meaning 'to stride broadly' to a distant place.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "趋在这里是", p: "qū zài zhè lǐ shì"}, {w: "走向机杼", p: "zǒu xiàng jī zhù"}, "，", {w: "并不是指远行", p: "bìng bú shì zhǐ yuǎn xíng"}, "。"], explanationEn: "Incorrect. 'Qū' means moving swiftly towards the weaving machine here, not going away to a far destination." }
        ]
    },
    {
        id: 2,
        textStructure: [{w: "乐羊子妻", p: "lè yáng zǐ qī"}, {w: "用织布来类比", p: "yòng zhī bù lái lèi bǐ"}, {w: "求学中的", p: "qiú xué zhōng de"}, "“", {w: "中道而归", p: "zhōng dào ér guī"}, "”", {w: "，", "主要是想强调"}, {w: "读书应当", p: "dú shū yīng dāng"}, "？"],
        en: "Why did the wife use weaving to critique his returning halfway ('中道而归')?",
        options: [
            { textStructure: [{w: "需要掌握巧妙的", p: "xū yào zhǎng wò qiǎo miào de"}, {w: "学习方法", p: "xué xí fāng fǎ"}, "，", {w: "不能只一味盲目苦读", p: "bù néng zhǐ yí wèi máng mù kǔ dú"}], en: "One must master flexible study techniques rather than memorizing blindly.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "类比的焦点是", p: "lèi bǐ de jiáo diǎn shì"}, {w: "时间积累的持续性", p: "shí jiān jī lěi de chí xù xìng"}, "，", {w: "而非技巧", p: "ér fēi jì qiǎo"}, "。"], explanationEn: "Incorrect. Her core focus was on the continuity of time and long commitment, not study techniques." },
            { textStructure: [{w: "需要坚持不懈的", p: "xū yào jiān chí bú xiè de"}, {w: "长久积累", p: "cháng jiǔ jī lěi"}, "，", {w: "绝不可中途半途而废", p: "jué bù kě zhōng tú bàn tú ér fèi"}], en: "One requires continuous, long accumulation and must never quit halfway.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "一丝一缕积累成布", p: "yì sī yì lǚ jī lěi chéng bù"}, "，", {w: "中途放弃则", p: "zhōng tú fàng qì zé"}, "“", {w: "捐失成功", p: "juān shī chéng gōng"}, "”", "。"], explanationEn: "Correct. Fabric is built thread by thread; cutting it halfway ruins all progress ('捐失成功')." },
            { textStructure: [{w: "需要明确合理的", p: "xū yào míng què hé lǐ de"}, {w: "长远目标", p: "cháng yuǎn mù biāo"}, "，", {w: "避免浪费宝贵的光阴", p: "bì miǎn làng fèi bǎo guì de guāng yīn"}], en: "One needs clear, long-term targets to avoid wasting valuable days.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "虽然提到了时日", p: "suī rán tí dào le shí rì"}, "，", {w: "但重点在行为的", p: "dàn zhòng diǎn zài xíng wéi de"}, {w: "持之以恒", p: "chí zhī yǐ héng"}, "。"], explanationEn: "Incorrect. While time was mentioned, the absolute emphasis was on perseverance rather than target setting." },
            { textStructure: [{w: "需要选择良好清净的", p: "xū yào xuǎn zé liáng hǎo qīng jìng de"}, {w: "求学环境", p: "qiú xué huán jìng"}, "，", {w: "从而阻断对家乡的思念", p: "cóng ér zǔ duàn duì jiā xiāng de sī niàn"}], en: "One should pick a quiet environment to block out homesickness entirely.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "方向完全想偏", p: "fāng xiàng wán quán xiǎng piān"}, "，", {w: "课文未曾提及", p: "kè wén wèi céng tí jí"}, {w: "环境问题", p: "huán jìn wèn tí"}, "。"], explanationEn: "Incorrect. This runs completely off track; the text never raised points about campus or regional conditions." }
        ]
    },
    {
        id: 3,
        textStructure: [{w: "关于", p: "guān yú"}, {w: "课文第二段中的", p: "kè wén dì èr duàn zhōng de"}, "“", {w: "日知其所亡", p: "rì zhī qí suǒ wáng"}, "”", {w: "，", "下列含义说明"}, {w: "正确的是", p: "zhèng què de shì"}, "？"],
        en: "Which explanation regarding the phrase 'rì zhī qí suǒ wáng' is correct?",
        options: [
            { textStructure: [{w: "每天都要去清除", p: "měi tiān dōu yào qù qīng chú"}, {w: "自己心里死板的", p: "zì jǐ xīn lǐ sǐ bǎn de"}, {w: "旧错旧错缺点", p: "jiù cuò quē diǎn"}], en: "Every day one must clear out his old mental mistakes and personal faults.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，“", {w: "亡", p: "wáng"}, "”", {w: "是通假字", p: "shì tōng jiǎ zì"}, "，", {w: "指的是没有的知识", p: "zhǐ de shì méi yǒu de zhī shi"}, "。"], explanationEn: "Incorrect. '亡' is a loan character for '无', meaning things one lacks or doesn't know yet, not personal faults." },
            { textStructure: [{w: "每天都要去反省", p: "měi tiān dōu yào qù fǎn xǐng"}, {w: "自己学业中", p: "zì jǐ xué yè zhōng"}, {w: "荒废流失的", p: "huāng fèi liú shī de"}, {w: "宝贵光阴", p: "bǎo guì guāng yīn"}], en: "Every day one must regret the wasted time and lost hours in his studies.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这误把“亡”", p: "zhè wù bǎ wáng"}, {w: "字面曲解成了", p: "zì miàn qū jiě chéng le"}, "“", {w: "死亡流失", p: "sǐ wáng liú shī"}, "”", "。"], explanationEn: "Incorrect. This takes the literal modern meaning of 'loss/death', entirely breaking classical semantics." },
            { textStructure: [{w: "每天都要去学习", p: "měi tiān dōu yào qù xué xí"}, {w: "自己以前", p: "zì jǐ yǐ qián"}, {w: "不知道的", p: "bù zhī dào de"}, {w: "新学问新知识", p: "xīn xué wèn"}], en: "Every day one should acquire new knowledge that he did not know before.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，“", {w: "亡", p: "wáng"}, "”", {w: "通“无”", p: "tōng wú"}, "，", {w: "指不晓得的学问", p: "zhǐ bù xiǎo de de xué wèn"}, "。"], explanationEn: "Correct. '亡' acts as '无', advising the reader to fill his daily intellectual blanks with fresh knowledge." },
            { textStructure: [{w: "每天都要去防范", p: "měi tiān dōu yào qù fáng fàn"}, {w: "自己财物中", p: "zì jǐ cái wù zhōng"}, {w: "被盗丢损的", p: "bèi dào diū sǔn de"}, {w: "各种金钱", p: "gè zhǒng jīn qián"}], en: "Every day one must protect his properties from being lost or stolen.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "把学术术语", p: "bǎ xué shù shù yǔ"}, {w: "误解成了生活安保", p: "wù jiě chéng le shēng huó ān bǎo"}, "。"], explanationEn: "Incorrect. This mistakes an academic proverb for financial property protection advice, completely missing the boat." }
        ]
    },
    {
        id: 4,
        textStructure: [{w: "妻子面对婆婆", p: "qī zi miàn duì pó po"}, {w: "偷杀邻居鸡肉时", p: "tōu shā lín jū jī ròu shí"}, "，", {w: "采取了", p: "cǎi qǔ le"}, "“", {w: "不餐而泣", p: "bù cān ér qì"}, "”", {w: "的举动", p: "de jǔ dòng"}, "，", {w: "主要表明", p: "zhǔ yào biǎo míng"}, "？"],
        en: "What did her dramatic reaction 'bù cān ér qì' (refusing to eat and weeping) over the chicken prove?",
        options: [
            { textStructure: [{w: "内心极度痛恨婆婆", p: "nèi xīn jí dù tòng hèn pó po"}, {w: "贪小便宜的", p: "tān xiǎo pián yi de"}, {w: "自私行为", p: "zì sī xíng wéi"}], en: "She secretly hated her mother-in-law's cheap and selfish behaviors.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "她哀伤的是", p: "tā āi shāng de shì"}, {w: "家庭因贫困", p: "jiā tíng yīn pín kùn"}, {w: "而导致品行有污", p: "ér dǎo zhì pǐn xíng yǒu wū"}, "。"], explanationEn: "Incorrect. She mourned that poverty forced their household into moral compromise, not out of raw hatred for her elder." },
            { textStructure: [{w: "坚守洁身自好的", p: "jiān shǒu jié shēn zì hào de"}, {w: "道德底线", p: "dào dé dǐ xiàn"}, "，", {w: "耻于吃偷来之物", p: "chǐ yú chī tōu lái zhī wù"}], en: "She strictly guarded her moral baseline, refusing to touch stolen food.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "她通过哭泣", p: "tā tōng guò kū qì"}, {w: "委婉表达劝谏", p: "wěi wǎn biǎo dá quàn jiàn"}, "，", {w: "成功让婆婆惭愧丢弃之", p: "chéng gōng ràng pó po cán kuì diū qì zhī"}, "。"], explanationEn: "Correct. Her non-violent protest ('not eating') gently corrected her elder, successfully inducing shame in the mother." },
            { textStructure: [{w: "害怕邻居发现后", p: "hài pà lín jū fā xiàn hòu"}, {w: "会前来兴师问罪", p: "huì qián lái xīng shī wèn zhèn"}, "，", {w: "给自己带来无限麻烦", p: "gěi zì jǐ dài lái máng fán"}], en: "She was terrified that neighbors would find out and cause major trouble.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这流于小人市侩心理", p: "zhè liú yú xiǎo rén shì kuài xīn lǐ"}, "，", {w: "完全不配贞义称号", p: "wán quán bú pèi zhēn yì chēng hào"}, "。"], explanationEn: "Incorrect. This reduces a noble hero's ethical stance to a cowardly fear of gossip, failing her tragic profile." },
            { textStructure: [{w: "同情伤心小鸡的", p: "tóng qíng shāng xīn jī de"}, {w: "悲惨遭遇", p: "bēi cǎn zāo yù"}, "，", {w: "无法忍受无辜杀戮", p: "wú fǎ rèn shòu wú gū shā lù"}], en: "She felt intense pity for the lost chicken and hated animal slaughter.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "这是现代动保观念", p: "zhè shì xiàn dài dòng bǎo guān niàn"}, "，", {w: "曲解了古文儒家廉洁核心", p: "qū jiě le gǔ wén rú jiā lián jié hé xīn"}, "。"], explanationEn: "Incorrect. This projects modern animal welfare values onto a classical text that focuses strictly on the theme of integrity." }
        ]
    },
    {
        id: 5,
        textStructure: [{w: "太守最后", p: "tài shǒu zuì hòu"}, {w: "追封妻子谥号为", p: "zhuī fēng qī zi shì hào wéi"}, "“", {w: "贞义", p: "zhēn yì"}, "”", {w: "，", "主要是为了赞扬"}, {w: "她什么样的行为", p: "tā zěnyàng de xíng wéi"}, "？"],
        en: "Why did the local governor award her the high posthumous title 'Zhenyi'?",
        options: [
            { textStructure: [{w: "面对盗贼强暴时", p: "miàn duì dào zéi qiáng bào shí"}, {w: "勇于操刀反抗", p: "yǒng yú cāo dāo fǎn kàng"}, "，", {w: "成功击退敌人的英勇", p: "chéng gōng jī tuì dí rén de yīng yǒng"}], en: "Her raw bravery in holding a weapon to fight criminals and successfully repelling them.", correct: false, explanationStructure: [{w: "错误", p: "cuò wù"}, "，", {w: "她最终自尽了", p: "tā zuì zhōng zì jìn le"}, "，", {w: "没有击退敌人", p: "méi yǒu jī tuì dí rén"}, "。"], explanationEn: "Incorrect. She tragically committed suicide to resolve the deadlock; she did not physically overpower or beat the bandits." },
            { textStructure: [{w: "宁可刎颈自尽也", p: "nìng kě wěn jǐng zì jìn yě"}, {w: "绝不屈从强盗", p: "jué bù qū cóng qiáng dào"}, "，", {w: "誓死捍卫贞洁与正义", p: "shì sǐ hàn wèi zhēn jié yǔ zhèng yì"}], en: "Her choice to slit her throat rather than yield, fiercely guarding her honor.", correct: true, explanationStructure: [{w: "正确", p: "zhèng què"}, "，", {w: "贞代表坚守妇德", p: "zhēn dài biǎo jiān shǒu fù dé"}, "，", {w: "义代表舍生取义", p: "yì dài biǎo shě shēng qǔ yì"}, "，", {w: "当之无愧", p: "dāng zhī wú kuì"}, "。"], explanationEn: "Correct. 'Zhen' represents unyielding moral purity, and 'Yi' signals sacrificing her life for justice." },
            { textStructure: [{w: "在家庭生活中能", p: "zài jiā tíng shēng huó zhōng néng"}, {w: "悉心侍奉婆婆", p: "xī xīn shì fèng pó po"}, "，", {w: "无怨无悔任劳任怨的付出", p: "wú yuàn wú huǐ rèn láo rèn yuàn"}], en: "Her excellent domestic performance in taking care of her old mother-in-law without complaints.", correct: false, explanationStructure: [{w: "不准确", p: "bú zhǔn què"}, "，", {w: "孝顺虽是美德", p: "xiào shùn suī ..."}, {w: "但“贞义”核心在", p: "dàn zhēn yì hé xīn ..."}, {w: "生死关头的浩然正气", p: "shēng sǐ guān tóu de"}, "。"], explanationEn: "Incorrect. Filial piety is fine, but the title specifically honors her extraordinary moral courage during the fatal crisis." },
            { textStructure: [{w: "极具聪明才智且", p: "jí jù cōng míng cái zhì qiě"}, {w: "善于运用言辞", p: "shàn yú yùn yòng yán cí"}, "，", {w: "开导劝勉丈夫成才", p: "kāi dǎo quàn miǎn zhàng fū chéng cái"}], en: "Her high intelligence and communication skills in pushing her husband to succeed.", correct: false, explanationStructure: [{w: "不全面", p: "bù quán miàn"}, "，", {w: "这只是前半段的贤惠", p: "zhè zhǐ shì qián bàn duàn de"}, {w: "不足以概括最终的", p: "bù zú yǐ gài kuò zuì zhōng de"}, {w: "烈女封号", p: "liè nǚ fēng hào"}, "。"], explanationEn: "Incorrect. This covers her advisory role in the first half of the story but fails to account for the extreme sacrifice at the end." }
        ]
    }
];
