const poemData = [
    // 🎯【第一段】：交代乐羊子妻的身世背景
    { text: "河南", py: "hé nán", zh: "河南，汉代郡名，这里指河南郡。", en: "In Henan Prefecture," },
    { text: "乐羊子", py: "lè yáng zǐ", zh: "乐羊子，故事中的男主角。", en: "Leyangzi's" },
    { text: "之", py: "zhī", zh: "助词，的。", en: "" },
    { text: "妻者", py: "qī zhě", zh: "<strong>妻者</strong>：……的妻子。者，表提起话题的助词。", en: "wife" },
    { text: "，", punc: true },
    { 
        text: "不知何氏", 
        py: "bù zhī hé shì", 
        zh: "<strong>大意</strong>：不知道是哪一家的。<br><strong>不知</strong>：动词短语，不知道。<br><strong>何氏</strong>：哪一氏、哪一家。", 
        en: "was not known which clan she came from,", 
        exam: true 
    },
    { text: "之", py: "zhī", zh: "的。", en: "" },
    { text: "女也", py: "nǚ yě", zh: "女儿。<strong>也</strong>：文言句末判断语气词，表陈述。", en: "or whose daughter she was." },
    { text: "。", punc: true, isParagraphEnd: true }, // 👈 🎯【第1段结束，强制分段】

    // 🎯【第二段】：路遗金饼，羞惭捐金
    { text: "羊子", py: "lè yáng zǐ", zh: "乐羊子。", en: "Leyangzi" },
    { text: "尝行路", py: "cháng xíng lù", zh: "<strong>词组大意</strong>：曾经在路上行走。尝：副词，曾经。", en: "was once walking along a road," },
    { text: "，", punc: true },
    { 
        text: "得遗金一饼", 
        py: "dé yí jīn yī bǐng", 
        zh: "<strong>大意</strong>：捡到一块别人丢弃的金饼。<br><strong>得</strong>：捡到、获得。<br><strong>遗金</strong>：丢失的金子。<br><strong>一饼</strong>：一块（汉代金子常铸成饼状）。", 
        en: "and found a piece of lost gold,", 
        exam: true 
    },
    { text: "，", punc: true },
    { text: "还以与妻", py: "huán yǐ yǔ qī", zh: "<strong>大意</strong>：回家后把它拿给妻子。以：介词，把（它）；与：动词，给。", en: "and brought it back to give to his wife." },
    { text: "。", punc: true },
    { text: "妻", py: "qī", zh: "妻子。", en: "His wife" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "妾", py: "qiè", zh: "代词，古代妇女的谦称，相当于“我”。", en: "I" },
    { text: "闻", py: "wén", zh: "动词，听说。", en: "have heard that" },
    { 
        text: "志士不饮", 
        py: "zhì shì bù yǐn", 
        zh: "<strong>名式大意</strong>：有志气的人不喝。<br><strong>志士</strong>：有远大志向与操守的人。<br><strong>不饮</strong>：动词短语，绝不饮用。", 
        en: "a man of purpose will not drink" 
    },
    { text: "‘", punc: true },
    { text: "盗泉", py: "dào quán", zh: "盗泉，泉水名（因名称不好听，廉洁之士嫌恶它而不喝）。", en: "In Henan Prefecture," },
    { text: "’", punc: true },
    { text: "之", py: "zhī", zh: "的。", en: "" },
    { text: "水", py: "shuǐ", zh: "水。", en: "water," },
    { text: "，", punc: true },
    { 
        text: "廉者不受", 
        py: "lián zhě bú shòu", 
        zh: "<strong>名式大意</strong>：廉洁的人绝不接受。<br><strong>廉者</strong>：廉洁正直的人。<br><strong>不受</strong>：动词短语，绝不接受。", 
        en: "and a person of integrity will not accept" 
    },
    { text: "嗟来之食", py: "jiē lái zhī shí", zh: "<strong>成语大意</strong>：带有侮辱性的施舍（带有‘喂，来吃！’傲慢语气的食物）。", en: "food offered in contempt," },
    { text: "，", punc: true },
    { 
        text: "况拾遗求利", 
        py: "kuàng shí yí qiú lì", 
        zh: "<strong>大意</strong>：更何况捡拾别人丢失的东西来谋求私利。<br><strong>况</strong>：何况。<br><strong>拾遗</strong>：捡拾丢失的东西。<br><strong>求利</strong>：谋求私利。", 
        en: "how much less should one pick up lost items for profit", 
        exam: true 
    },
    { 
        text: "以污其行乎", 
        py: "yǐ wū qí xíng hū", 
        zh: "<strong>大意</strong>：以此来玷污自己的品行呢！<br><strong>以</strong>：连词，来。<br><strong>污</strong>：使动用法，玷污。<br><strong>乎</strong>：句末反问语气词，呢。", 
        en: "to stain his own conduct!", 
        exam: true 
    },
    { text: "！", punc: true },
    { text: "”", punc: true },
    { text: "羊子大惭", py: "yáng zǐ dà cán", zh: "<strong>词组大意</strong>：乐羊子感到非常羞愧。大：副词，非常。", en: "Leyangzi felt deeply ashamed," },
    { text: "，", punc: true },
    { text: "乃捐金于野", py: "nǎi juān jīn yú yě", zh: "<strong>大意</strong>：于是把金子丢弃在荒野里。乃：于是；捐：丢弃；于：在。", en: "so he threw the gold in the wilderness," },
    { text: "，", punc: true },
    { text: "而远寻师学", py: "ér yuǎn xún shī xué", zh: "<strong>大意</strong>：然后到远方去寻找老师学习。而：表顺接连词。", en: "and traveled far away to find a master to study." },
    { text: "。", punc: true, isParagraphEnd: true }, // 👈 🎯【第2段结束，强制分段】

    // 🎯【第三段】：引刀断织，复还终业
    { text: "一年归来", py: "yī nián guī lái", zh: "过了一年，乐羊子返回家中。", en: "One year later, he returned home," },
    { text: "，", punc: true },
    { text: "妻跪问其故", py: "qī guì wèn qí gù", zh: "<strong>大意</strong>：妻子跪着询问他回家的原因。跪：汉代古人席地而坐，直身表示敬意；故：原因。", en: "his wife knelt and asked him the reason for his return." },
    { text: "，", punc: true },
    { text: "羊子", py: "lè yáng zǐ", zh: "乐羊子。", en: "Leyangzi" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "久行怀思", py: "jiǔ xíng huái sī", zh: "<strong>大意</strong>：出门久了，心中思念家里。久行：出门在外时间长；怀思：思念。", en: "Traveling for so long, I missed home," },
    { text: "，", punc: true },
    { 
        text: "无它异也", 
        py: "wú tā yì yě", 
        zh: "<strong>大意</strong>：没有别的原因。<br><strong>无它</strong>：没有别的。<br><strong>异</strong>：奇异的事、别的缘故。", 
        en: "there is no other reason." 
    },
    { text: "。", punc: true },
    { text: "”", punc: true },
    { text: "妻乃引刀趋机", py: "qī nǎi yǐn dāo qū jī", zh: "<strong>大意</strong>：妻子于是拿起刀走向织布机。乃：于是；引：拿、操起；趋：快步走向。", en: "His wife then took a knife, ran to the loom," },
    { text: "而", py: "ér", zh: "连词，表顺接，并且。", en: "and" },
    { text: "言", py: "yán", zh: "动词，说。", en: "spoke" },
    { text: "曰", py: "yuē", zh: "说。", en: "saying," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { 
        text: "此织生自蚕茧", 
        py: "cǐ zhī shēng zì cán jiǎn", 
        zh: "<strong>大意</strong>：这块布匹料子是从蚕茧里抽丝出来的。<br><strong>此织</strong>：这件织物。<br><strong>自</strong>：从。", 
        en: "This cloth began from a silkworm cocoon" 
    },
    { text: "，", punc: true },
    { text: "成于机杼", py: "chéng yú jī zhù", zh: "<strong>大意</strong>：在织布机上织成的。于：在；机杼：织布机和梭子。", en: "and was completed on the loom." },
    { text: "。", punc: true },
    { text: "一丝而累", py: "yī sī ér lěi", zh: "<strong>大意</strong>：一根丝一根丝地积累起来。累：积累。", en: "Accumulated thread by thread," },
    { text: "，", punc: true },
    { text: "以至于寸", py: "yǐ zhì yú cùn", zh: "从而积累到一寸。以至于：层进连词，发展到。", en: "it grows into inches;" },
    { text: "，", punc: true },
    { text: "累寸不已", py: "lěi cùn bù yǐ", zh: "<strong>词组大意</strong>：不停地积累一寸。不已：不停止、不停。", en: "accumulating inches without stopping," },
    { text: "，", punc: true },
    { text: "遂成丈匹", py: "suì chéng zhàng pǐ", zh: "<strong>大意</strong>：于是才成为一丈一匹的布。遂：于是、最终。", en: "it finally becomes full yards of cloth." },
    { text: "。", punc: true },
    { 
        text: "今若断斯织也", 
        py: "jīn ruò duàn sī zhī yě", 
        zh: "<strong>大意</strong>：现在如果割断这块正在织的布。<br><strong>若</strong>：如果。<br><strong>斯</strong>：代词，这。<br><strong>断</strong>：割断。", 
        en: "Now if you cut this cloth," 
    },
    { text: "，", punc: true },
    { 
        text: "则捐失成功", 
        py: "zé juān shī chéng gōng", 
        zh: "<strong>大意</strong>：就会丢弃和损失已经取得的成果。<br><strong>则</strong>：就。<br><strong>捐失</strong>：丢弃、损失。", 
        en: "you throw away and lose the achieved work,", 
        exam: true 
    },
    { 
        text: "稽废时日", 
        py: "jī fèi shí rì", 
        zh: "<strong>大意</strong>：荒废耽误时日。<br><strong>稽</strong>：迟延、耽误。<br><strong>废</strong>：荒废、废弃。", 
        en: "and waste your valuable days.", 
        exam: true 
    },
    { text: "。", punc: true },
    { text: "夫子积学", py: "fū zǐ jī xué", zh: "<strong>词组大意</strong>：您积累学识。夫子：对男子的尊称，相当于‘您’；积学：积累学问。", en: "My husband, your accumulation of knowledge" },
    { text: "，", punc: true },
    { text: "当‘日知其所亡’", py: "dāng rì zhī qí suǒ wáng", zh: "<strong>大意</strong>：应该每天学习自己所不知道的知识。亡：通‘无’，没有、不晓得的。", en: "should let you know what you lack every day," },
    { text: "，", punc: true },
    { text: "以就懿德", py: "yǐ jiù yì dé", zh: "<strong>大意</strong>：来成就美德。以：连词，来；就：成就；懿德：美德。", en: "so as to achieve noble virtue;" },
    { text: "；", punc: true },
    { text: "若中道而归", py: "ruò zhōng dào ér guī", zh: "<strong>大意</strong>：如果半路停下来回家。中道：半路、中途。", en: "if you return halfway through," },
    { text: "，", punc: true },
    { 
        text: "何异断斯织乎", 
        py: "hé yì duàn sī zhī hū", 
        zh: "<strong>句式大意</strong>：跟割断这块布有什么区别呢！<br><strong>何异</strong>：有什么不同、有什么区别。<br><strong>乎</strong>：句末反问语气词，呢。", 
        en: "how is it different from cutting this cloth!", 
        exam: true 
    },
    { text: "？", punc: true },
    { text: "”", punc: true },
    { text: "羊子感其言", py: "yáng zǐ gǎn qí yán", zh: "<strong>词组大意</strong>：乐羊子被她的话所感动。感：被……感动。", en: "Leyangzi was deeply moved by her words," },
    { text: "，", punc: true },
    { text: "复还终业", py: "fù huán zhōng yè", zh: "<strong>词组大意</strong>：再次回去完成学业。复：再次；终业：完成学业。", en: "returned once again to complete his studies," },
    { text: "，", punc: true },
    { text: "遂七年不返", py: "suì qī nián bù fǎn", zh: "<strong>词组大意</strong>：于是整整七年没有回家。不返：没有返回。", en: "and did not return home for seven years." },
    { text: "。", punc: true, isParagraphEnd: true }, // 👈 🎯【第3段结束，强制分段】

    // 🎯【第四段】：邻鸡谬入，不餐而泣
    { text: "尝有它舍鸡", py: "cháng yǒu tā shè jī", zh: "<strong>大意</strong>：曾经有别人家的一只鸡。它舍：别家、邻居。", en: "Once, a neighbor's chicken" },
    { 
        text: "谬入园中", 
        py: "miù rù yuán zhōng", 
        zh: "<strong>大意</strong>：错误地跑进自家的菜园子里。<br><strong>谬</strong>：副词，错误地、迷路地。<br><strong>园中</strong>：菜园子里面。", 
        en: "mistakenly entered their garden," 
    },
    { text: "，", punc: true },
    { text: "姑盗杀而食之", py: "gū dào shā ér shí zhī", zh: "<strong>大意</strong>：婆婆偷抓来杀了并把它吃了。姑：婆婆；盗：偷窃、偷偷地。", en: "his mother secretly killed it and cooked it to eat." },
    { text: "，", punc: true },
    { 
        text: "妻对鸡不餐而泣", 
        py: "qī duì jī bù cān ér qì", 
        zh: "<strong>大意</strong>：妻子对着鸡肉一口也不吃，反而流下眼泪。<br><strong>不餐</strong>：不吃饭、不吃肉。<br><strong>泣</strong>：流泪。", 
        en: "Leyangzi's wife faced the chicken meat, refused to eat, and wept." 
    },
    { text: "。", punc: true },
    { text: "姑怪问其故", py: "gū guài wèn qí gù", zh: "<strong>大意</strong>：婆婆感到奇怪，责问她原因。怪：意动用法，以……为怪，感到奇怪。", en: "The mother found it strange and asked her why." },
    { text: "。", punc: true },
    { text: "妻", py: "qī", zh: "妻子。", en: "The wife" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "自伤居贫", py: "zì shāng jū pín", zh: "<strong>词组大意</strong>：自己伤心家里贫穷。自伤：自己哀伤；居贫：生活贫困。", en: "I am mourning because we live in such poverty" },
    { text: "，", punc: true },
    { text: "使食有它肉", py: "shǐ shí yǒu tā ròu", zh: "<strong>大意</strong>：才使得饭桌上竟然出现了别人家的肉。使：导致；它肉：别人的肉。", en: "that it caused neighbor's meat to be served on our table." },
    { text: "。", punc: true },
    { text: "”", punc: true },
    { text: "姑竟弃之", py: "gū jìng qì zhī", zh: "<strong>大意</strong>：婆婆听完感到惭愧，最终把肉倒掉不吃了。竟：最终；弃：丢弃。", en: "The mother felt ashamed and finally threw it away." },
    { text: "。", punc: true, isParagraphEnd: true }, // 👈 🎯【第4段结束，强制分段】

    // 🎯【第五段】：盗贼劫姑，刎颈全贞
    { text: "后盗欲有犯妻者", py: "hòu dào yù yǒu fàn qī zhě", zh: "<strong>大意</strong>：后来有强盗想要侵犯乐羊子妻。犯：侵犯、非礼。", en: "Later, a bandit wanted to assault the wife," },
    { text: "，", punc: true },
    { text: "乃先劫其姑", py: "nǎi xiān jié qí gū", zh: "<strong>大意</strong>：强盗就先挟持绑架了她的婆婆。劫：劫持、挟持威胁。", en: "so he first kidnapped her mother-in-law." },
    { text: "。", punc: true },
    { text: "妻闻", py: "qī wén", zh: "妻子听到了这个消息。", en: "Hearing this, the wife" },
    { text: "，", punc: true },
    { text: "操刀而出", py: "cāo dāo ér chū", zh: "<strong>词组大意</strong>：手里拿着刀立刻冲了出来。操：拿着、握着。", en: "held a knife and ran out." },
    { text: "。", punc: true },
    { text: "盗人", py: "dào rén", zh: "强盗。", en: "The bandit" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "释汝刀从我者可全", py: "shì rǔ dāo cóng wǒ zhě kě quán", zh: "<strong>大意</strong>：放下你的刀顺从我，你就能保全生命。释：放下；汝：你；全：保全活命。", en: "If you drop your knife and follow me, you will be safe;" },
    { text: "，", punc: true },
    { text: "不从我者", py: "bù cóng wǒ zhě", zh: "<strong>大意</strong>：如果不顺从我。不从：不听从、不顺从。", en: "if you do not follow me," },
    { text: "，", punc: true },
    { text: "则杀汝姑", py: "zé shā rǔ gū", zh: "<strong>大意</strong>：我就立刻杀了你的婆婆。则：就；汝姑：你的婆婆。", en: "I will kill your mother-in-law." },
    { text: "。”", punc: true },
    { text: "妻仰天而叹", py: "qī yǎng tiān ér tàn", zh: "<strong>词组大意</strong>：妻子仰面朝天发出长叹。仰天：抬头看天。", en: "The wife looked up to the sky and sighed," },
    { text: "，", punc: true },
    { text: "举刀刎颈而死", py: "jǔ dāo wěn jǐng ér sǐ", zh: "<strong>大意</strong>：举起刀割断自己的脖子自尽了。刎颈：割脖子自杀。", en: "then raised the knife, cut her own throat, and died." },
    { text: "。", punc: true },
    { text: "盗亦不杀其姑", py: "dào yì bù shā qí gū", zh: "<strong>词组大意</strong>：强盗被震撼了，也最终没有杀她的婆婆。不杀：没杀。", en: "The bandit was shocked and did not kill her mother-in-law either." },
    { text: "。", punc: true },
    { text: "太守闻之", py: "tài shǒu wén zhī", zh: "<strong>词组大意</strong>：当地的太守官长听说了这件壮烈的事。太守：汉代郡的长官。", en: "The local governor heard of this," },
    { text: "，", punc: true },
    { text: "即捕杀贼盗", py: "jí bǔ shā zéi dào", zh: "<strong>大意</strong>：立刻下令逮捕并处死了那个贼寇强盗。即：立刻；捕杀：逮捕处死。", en: "immediately captured and executed the bandit," },
    { text: "，", punc: true },
    { text: "而赐妻缣帛", py: "ér cì qī jiān bó", zh: "<strong>大意</strong>：并且赏赐给乐羊子家大批优质丝织品。赐：赏赐；缣帛：丝织品。", en: "and rewarded her family with fine silk fabric," },
    { text: "，", punc: true },
    { text: "以礼葬之", py: "yǐ lǐ zàng zhī", zh: "<strong>大意</strong>：按照崇高的礼节隆重安葬了她。以：用；之：指代乐羊子妻。", en: "burying her with grand respect and rituals," },
    { text: "，", punc: true },
    { text: "号曰", py: "hào yuē", zh: "<strong>词组大意</strong>：追封其谥号称作。号曰：封称号为。", en: "and honoring her title as" },
    { text: "“", punc: true },
    { text: "贞义", py: "zhēn yì", zh: "贞义（贞洁烈女、坚守正义）。", en: "Virtuous and Righteous." },
    { text: "”", punc: true },
    { text: "。", punc: true }
];
